app/accounts/forms.py
"""
Contains forms to render in accounts blueprint templates.
"""

from flask_wtf import FlaskForm, RecaptchaField
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, FileField
from wtforms.validators import DataRequired, Length, Email, EqualTo

from .utils import PasswordType, UniqueEmail, UniqueUsername, PasswordOfCurrentUser, DeleteSlug


class RegistrationForm(FlaskForm):
    """Form get user data during registration."""

    username = StringField(
        'Username',
        validators=[
            DataRequired('This field is required.'),
            Length(min=3, max=50),
            UniqueUsername('This username is already taken.'),
        ]
    )

    email = StringField(
        'Email',
        validators=[
            DataRequired('This field is required.'),
            Length(min=5, max=100),
            Email(),
            UniqueEmail('This email is already taken, please select another one.'),
        ]
    )

    password = PasswordField(
        'Password',
        validators=[
            DataRequired('This field is required.'),
            Length(min=6, max=100),
            PasswordType(
                'Make sure your password has a number in it.',
                'Make sure your password has a letter in it.',
                'Make sure your password has a capital letter in it.'
            ),
        ]
    )

    confirm_password = PasswordField(
        'Password confirmation',
        validators=[
            DataRequired('This field is required.'),
            EqualTo('password'),
        ]
    )

    recaptcha = RecaptchaField()

    submit = SubmitField(
        'Register'
    )


class LoginForm(FlaskForm):
    """Form get user credentials during authentication."""

    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Email(),
        ]
    )

    password = PasswordField(
        'Password',
        validators=[
            DataRequired(),
        ]
    )

    remember = BooleanField(
        'Remember me'
    )

    submit = SubmitField(
        'Log in'
    )


class AccountUpdateForm(FlaskForm):
    """Form get user data while updating information about him."""

    username = StringField(
        'Username',
        validators=[
            Length(min=3, max=50),
            UniqueUsername('This username is already taken.'),
        ]
    )

    email = StringField(
        'Email',
        validators=[
            Length(min=5, max=100),
            Email(),
            UniqueEmail('This email is already taken, please select another one.'),
        ]
    )

    description = StringField(
        'Description',
    )

    image = FileField(
        'Image',
        validators=[
            FileAllowed(['png', 'jpg', 'jpeg'], 'Images only!')
        ]
    )

    use_gravatar = BooleanField(
        'Use gravatar'
    )

    submit = SubmitField(
        'Update'
    )


class ChangePasswordForm(FlaskForm):
    """Form get new password."""

    old_password = PasswordField(
        'Current password',
        validators=[
            DataRequired('This field is required.'),
            PasswordOfCurrentUser('Invalid current password.'),
        ]
    )

    new_password = PasswordField(
        'New password',
        validators=[
            DataRequired('This field is required.'),
            Length(min=6, max=100),
            PasswordType(
                'Make sure your password has a number in it.',
                'Make sure your password has a letter in it.',
                'Make sure your password has a capital letter in it.'
            ),
        ]
    )

    confirm_new_password = PasswordField(
        'New password confirmation',
        validators=[
            DataRequired('This field is required.'),
            EqualTo('new_password'),
        ]
    )

    submit = SubmitField(
        'Change'
    )


class DeleteAccountForm(FlaskForm):
    """Form get confirmation slug during deletions account."""

    REQUIRED_SLUG = 'delete'

    slug = StringField(
        'Confirm deletion',
        validators=[
            DeleteSlug(f'Invalid slug. Please type "{REQUIRED_SLUG}" to delete your account.', REQUIRED_SLUG),
        ]
    )

    submit = SubmitField(
        'Delete'
    )


class ResetPasswordEmailInputForm(FlaskForm):
    """Form get email to send reset password mali."""

    email = StringField(
        'Email',
        validators=[
            DataRequired('This field is required.'),
            Email(),
        ]
    )

    recaptcha = RecaptchaField()

    submit = SubmitField(
        'Send'
    )


class ResetPasswordNewPasswordInputForm(FlaskForm):
    """Form get new password."""

    password = PasswordField(
        'Password',
        validators=[
            DataRequired('This field is required.'),
            Length(min=6, max=100),
            PasswordType(
                'Make sure your password has a number in it.',
                'Make sure your password has a letter in it.',
                'Make sure your password has a capital letter in it.'
            ),
        ]
    )

    confirm_password = PasswordField(
        'Password confirmation',
        validators=[
            DataRequired('This field is required.'),
            EqualTo('password'),
        ]
    )

    submit = SubmitField(
        'Set'
    )

app/accounts/__init__.py
"""Module creates blueprint to manage users in keepno app."""

from .views import accounts_blueprint


__all__ = [
    'accounts_blueprint',
]

app/accounts/views.py
"""
Contains view functions for accounts blueprint.
"""

from flask import (Blueprint, render_template, redirect, url_for, flash, request, current_app, send_from_directory)
from flask.wrappers import Response
from flask_login import login_user, logout_user, login_required, current_user

from .models import User, Profile
from .utils import redirect_authenticated_users, active_account_required, save_picture, redirect_to_last_updated_note
from .messages import (
    CONFIRMATION_MAIL_SENT, INVALID_CREDENTIALS, ACCOUNT_CONFIRMED, ACCOUNT_JUST_CONFIRMED, INVALID_CONFIRMATION_LINK,
    NEW_CONFIRMATION_MAIL_SENT, ACCOUNT_UPDATED_SUCCESSFULLY, PASSWORD_CHANGED_SUCCESSFULLY,
    ACCOUNT_DELETED_SUCCESSFULLY, PASSWORD_RESET_SUCCESSFULLY
)
from .forms import (
    RegistrationForm, LoginForm, AccountUpdateForm, ChangePasswordForm, DeleteAccountForm, ResetPasswordEmailInputForm,
    ResetPasswordNewPasswordInputForm
)
from ..notes.models import Note


accounts_blueprint = Blueprint('accounts',  __name__, template_folder='templates')


@accounts_blueprint.route('/register', methods=['GET', 'POST'])
@redirect_authenticated_users
def register() -> str:
    """The view adds new user in keepno app."""
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = User.generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        user.save_to_db()
        profile = Profile(user=user)
        profile.generate_gravatar_url()
        profile.save_to_db()
        from .tasks import send_account_activation_email  # pylint: disable=import-outside-toplevel
        send_account_activation_email.delay(user.id)
        login_user(user)
        flash(CONFIRMATION_MAIL_SENT, 'success')
        return redirect(url_for('accounts.unconfirmed'))
    return render_template('accounts/register.html', form=form)


@accounts_blueprint.route('/login', methods=['GET', 'POST'])
@redirect_authenticated_users
def login() -> str:
    """The view logs in user."""
    form = LoginForm()
    if form.validate_on_submit():
        user = User.find_by_email(form.email.data)
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)
            if current_user.is_authenticated and not current_user.active:
                return redirect(url_for('accounts.unconfirmed'))
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            return redirect_to_last_updated_note()
        flash(INVALID_CREDENTIALS, 'error')
    return render_template('accounts/login.html', form=form)


@accounts_blueprint.route('/logout')
@login_required
def logout() -> str:
    """The view logs out user."""
    logout_user()
    return render_template('accounts/logout.html')


@accounts_blueprint.route('/unconfirmed')
@login_required
def unconfirmed() -> str:
    """The view notifies user about unconfirmed account."""
    if current_user.active:
        flash(ACCOUNT_CONFIRMED, 'warning')
        next_page = request.args.get('next')
        if next_page:
            return redirect(next_page)
        return redirect('accounts.account')
    return render_template('accounts/unconfirmed.html')


@accounts_blueprint.route('/account')
@login_required
def account() -> str:
    """The view renders user profile page."""
    number_of_notes = Note.count_user_notes(current_user.id)
    return render_template('accounts/account.html', number_of_notes=number_of_notes)


@accounts_blueprint.route('/confirm/<token>')
def activate_account(token: str) -> str:
    """The view activates user account."""
    user = User.verify_jwt_token(token)
    if user:
        user.active = True
        user.save_to_db()
        flash(ACCOUNT_JUST_CONFIRMED, 'success')
        if not current_user.is_authenticated:
            return redirect(url_for('accounts.login'))
        return redirect_to_last_updated_note()
    flash(INVALID_CONFIRMATION_LINK, 'error')
    return redirect(url_for('accounts.unconfirmed'))


@accounts_blueprint.route('/confirm')
@login_required
def resend_confirmation() -> Response:
    """The view sends mail with activation account link."""
    if current_user.active:
        flash(ACCOUNT_CONFIRMED, 'warning')
        return redirect_to_last_updated_note()
    from .tasks import send_account_activation_email  # pylint: disable=import-outside-toplevel
    send_account_activation_email.delay(current_user.id)
    flash(NEW_CONFIRMATION_MAIL_SENT)
    return redirect(url_for('accounts.unconfirmed'))


@accounts_blueprint.route('/media/accounts/img/<filename>')
@login_required
def media_user_img(filename: str) -> Response:
    """The view returns users profile image."""
    image_path = current_app.config['MEDIA_ROOT'] / 'accounts' / 'img'
    return send_from_directory(image_path, filename)


@accounts_blueprint.route('/account/update', methods=['GET', 'POST'])
@login_required
@active_account_required
def account_update() -> str:
    """The view updates user information."""
    form = AccountUpdateForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.change_email(form.email.data)
        current_user.save_to_db()
        current_user.profile.description = form.description.data
        if form.image.data and not form.use_gravatar.data:
            current_user.profile.image = save_picture(form.image.data)
            current_user.profile.custom_image = True
        if form.use_gravatar.data:
            current_user.profile.custom_image = False
        current_user.profile.save_to_db()
        flash(ACCOUNT_UPDATED_SUCCESSFULLY, 'success')
        return redirect(url_for('accounts.account'))
    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.description.data = current_user.profile.description
    return render_template('accounts/account_update.html', form=form)


@accounts_blueprint.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password() -> str:
    """The view changes current user password."""
    form = ChangePasswordForm()
    if form.validate_on_submit():
        hashed_password = User.generate_password_hash(form.new_password.data)
        current_user.password = hashed_password
        current_user.save_to_db()
        flash(PASSWORD_CHANGED_SUCCESSFULLY, 'success')
        return redirect(url_for('accounts.account'))
    return render_template('accounts/change_password.html', form=form)


@accounts_blueprint.route('/delete-account', methods=['GET', 'POST'])
@login_required
def delete_account() -> str:
    """The view deletes user account."""
    form = DeleteAccountForm()
    if form.validate_on_submit():
        # add user deletetion
        flash(ACCOUNT_DELETED_SUCCESSFULLY, 'success')
        return redirect(url_for('accounts.login'))
    return render_template('accounts/delete_account.html', form=form)


@accounts_blueprint.route('/reset-password-email-input', methods=['GET', 'POST'])
def reset_password_email_input() -> str:
    """The view sends email with link to reset password page."""
    form = ResetPasswordEmailInputForm()
    if form.validate_on_submit():
        from .tasks import send_reset_password_email  # pylint: disable=import-outside-toplevel
        send_reset_password_email.delay(form.email.data)
        return redirect(url_for('accounts.reset_password_email_sent'))
    return render_template('accounts/reset_password_email_input.html', form=form)


@accounts_blueprint.route('/reset-password-email-sent')
def reset_password_email_sent() -> str:
    """The view shows confirmation of sending email with reset password link."""
    return render_template('accounts/reset_password_email_sent.html')


@accounts_blueprint.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token: str) -> str:
    """The view resets user password."""
    user = User.verify_jwt_token(token)
    if not user:
        flash(INVALID_CONFIRMATION_LINK, 'error')
        return redirect(url_for('accounts.login'))
    form = ResetPasswordNewPasswordInputForm()
    if form.validate_on_submit():
        user.password = User.generate_password_hash(form.password.data)
        user.save_to_db()
        flash(PASSWORD_RESET_SUCCESSFULLY, 'success')
        return redirect(url_for('accounts.login'))
    return render_template('accounts/reset_password_new_password_input.html', form=form)

app/accounts/templates/accounts/account.html
{% extends "base.html" %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
{% endblock %}


{% block content %}

{% include "includes/header.html" %}

<!-- MAIN PAGE START -->
<div class="jumbotron my-3">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="margin-top: 80px;">
      <div class="col-md-6 col-lg-6 col-xl-6">
        <div class="card rounded-3 text-black">
          <div class="card-body mx-md-4 my-4 pb-1">
            <div class="text-center mb-4">
              <img src="{{ current_user.profile.user_image() }}" alt="mdo" width="200" height="200" class="rounded-circle mb-3">
              <div>
                <p class="lead">{{ current_user.username }}</p>
              </div>
              <div>
                <p class="">{{ current_user.email }}</p>
              </div>
              <div>
                <p class="" style="font-size: 1.6rem;"><b>{{ number_of_notes }}</b> notes</p>
              </div>
              <div>
                <span>You joined to as <span class="badge bg-secondary">{{ current_user.created.strftime('%d-%m-%Y') }}</span></span>
              </div>
            </div>
            <div class="mb-4 float-end">
              <a class="text-muted" href="{{ url_for('accounts.account_update') }}">
                <span>Edit profile</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-arrow-bar-right" 
                     viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6 8a.5.5 0 0 0 .5.5h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 
                                               0-.708l-3-3a.5.5 0 0 0-.708.708L12.293 7.5H6.5A.5.5 0 0 0 6 8zm-2.5 7a.5.5 0 0 
                                               1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5z"/>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- MAIN PAGE END -->

{% endblock %}


{% block js %}

<script src="{{ url_for('static', filename='js/header.bundle.js') }}"></script>

{% endblock %}

app/accounts/templates/accounts/account_update.html
{% extends "base.html" %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
{% endblock %}


{% block content %}

{% include "includes/header.html" %}

<!-- MAIN PAGE START -->
<div class="jumbotron my-3">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="margin-top: 80px;">
      <div class="col-md-6 col-lg-6 col-xl-6">
        <div class="card rounded-3 text-black">
          <div class="card-body mx-md-4 my-4 pb-1">
            <div class="mb-4">
              <div class="text-center">
              <p class="lead">Update your profile</p>
            </div>
              <form method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-outline mb-2">
                {{ form.username.label(class_="form-label") }}
                {{ form.username(class_="form-control", id_="form2Example11", placeholder="Your unique username") }}
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="form-outline mb-2">
                {{ form.email.label(class_="form-label") }}
                {{ form.email(class_="form-control", id_="form2Example22", placeholder="Your e-mail address") }}
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="form-outline mb-2">
                {{ form.description.label(class_="form-label") }}
                {{ form.description(class_="form-control", id_="form2Example33", placeholder="Write a few words about yourself") }}
                {% for error in form.description.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="mb-2">
                {{ form.image.label(class_="form-label") }}
                {{ form.image(class_="form-control", id_="form2Example44") }}
                {% for error in form.image.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="form-check mt-3 mb-2">
                {{ form.use_gravatar.label(class_="form-check-label") }}
                {{ form.use_gravatar(class_="form-check-input") }}
                {% for error in form.use_gravatar.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="mb-4">
                  <a class="text-muted" href="{{ url_for('accounts.change_password') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-key" 
                         viewBox="0 0 16 16">
                        <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 
                                 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 
                                 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 
                                 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 
                                 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z"/>
                        <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                      </svg>
                    <span>Change password</span>
                    
                  </a><br/>
                  <a class="text-muted" href="{{ url_for('accounts.delete_account') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash" 
                         viewBox="0 0 16 16">
                      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 
                               0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                      <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 
                                       1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 
                                       1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                    </svg>
                    <span>Delete account</span>
                  </a>
                </div>
                <div class="text-center mb-2">
                  <div class="d-grid gap-2">
                    <button class="btn btn-dark mb-2" type="submit">Update</button>
                  </div>
                </div>
                <div>
                  <a class="text-muted" href="{{ url_for('accounts.account') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-arrow-bar-left" 
                         viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5zM10 8a.5.5 0 0 
                                       1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 
                                       .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5z"/>
                    </svg>
                    <span>Go to profile</span>
                  </a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- MAIN PAGE END -->

{% endblock %}


{% block js %}

<script src="{{ url_for('static', filename='js/header.bundle.js') }}"></script>

{% endblock %}

app/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
<style>
  .gradient-custom-2 {
    /* fallback for old browsers */
    background: #fccb90;
    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, #000000, #424242, #696969, #b6b6b6);
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, #000000, #424242, #696969, #b6b6b6);
  }
  @media (min-width: 769px) {
    .gradient-custom-2 {
      border-top-right-radius: .3rem;
      border-bottom-right-radius: .3rem;
    }
  }   
</style>
{% endblock %}


{% block content %}

<div class="jumbotron d-flex align-items-center min-vh-100">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body mx-md-4 my-4">
                <div class="text-center mb-4">
                  <h1>
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" 
                          class="bi bi-box" viewBox="0 0 16 16">
                      <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 
                                4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 
                                1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 
                                0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
                    </svg>
                    <span> Keepno</span>
                  </h1>
                  <br/>
                  <h4>
                    <span style="color: rgb(0, 93, 175);">Keep</span> all your <span style="color: rgb(0, 93, 175);">no</span>tes in one place
                  </h4>
                </div>
                <form method="POST">
                  {{ form.csrf_token }}
                  <p class="lead">Please login to your account</p>
                  <div class="form-outline mb-2">
                    {{ form.email.label(class_="form-label") }}
                    {{ form.email(class_="form-control", id_="form2Example11", placeholder="Your e-mail address") }}
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  <div class="form-outline mb-2">
                    {{ form.password.label(class_="form-label") }}
                    {{ form.password(class_="form-control", id_="form2Example22", placeholder="Your secret password") }}
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  <div class="form-check my-3">
                    {{ form.remember.label(class_="form-check-label") }}
                    {{ form.remember(class_="form-check-input") }}
                    {% for error in form.remember.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  <div class="text-center mb-1">
                    <div class="d-grid gap-2">
                      <button class="btn btn-dark mb-2" type="submit">Login</button>
                      <a class="text-muted" href="{{ url_for('accounts.reset_password_email_input') }}">Forgot password?</a>
                    </div>
                  </div>
                  <div class="d-flex align-items-center justify-content-center mt-3">
                    <p class="mb-0 me-2">
                        <span>Don't have an account?</span>
                        <a href="{{ url_for('accounts.register') }}" role="button" class="btn btn-outline-danger btn-sm">Register</a>
                    </p>
                  </div>
                </form>
              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">We are more than just a company</h4>
                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}


{% block js %}
{% endblock %}

app/accounts/templates/accounts/unconfirmed.html
{% extends "base.html" %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
{% endblock %}


{% block content %}

{% include "includes/header.html" %}

<!-- MAIN PAGE START -->
<div class="jumbotron my-3">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="margin-top: 80px;">
      <div class="col-md-6 col-lg-6 col-xl-6">
        <div class="card rounded-3 text-black">
          <div class="card-body mx-md-4 my-4">
            <div class="text-center mb-4">
              <h1>
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-box" viewBox="0 0 16 16">
                  <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
                </svg>
                <span> Keepno</span>
              </h1>
              <br/>
              <h4>You have not confirmed your account yet.</h4>
              <p class="lead">You should have received an email with confirmation link.</p>
              <p class="lead">Need another confirmation email?
              <a href="{{ url_for('accounts.resend_confirmation') }}" role="button" class="btn btn-outline-danger btn-sm">Resend</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- MAIN PAGE END -->


{% endblock %}


{% block js %}
{% endblock %}