app/notes/forms.py
"""
Contains forms to render in notes blueprint templates.
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class AddFirstNoteForm(FlaskForm):
    """Form adds first Note."""

    title = StringField(
        'Title',
        validators=[
            DataRequired('This field is required.'),
            Length(min=3, max=50),
        ]
    )

    description = StringField(
        'Description',
        validators=[
            DataRequired('This field is required.'),
            Length(min=5, max=100),
        ]
    )

    submit = SubmitField(
        'Add note'
    )

app/notes/__init__.py
"""Module creates blueprint to manage notes in keepno app."""

from .views import notes_blueprint


__all__ = [
    'notes_blueprint',
]

app/notes/views.py
"""
Contains view functions for notes blueprint.
"""

from flask import (
    Blueprint, render_template, current_app, request, jsonify, make_response, abort, send_from_directory, redirect,
    url_for, flash
)
from flask.wrappers import Response
from marshmallow.exceptions import ValidationError
from flask_login import current_user

from .messages import (NO_DATA_TO_ADD, MISSING_JSON, NOTE_DOES_NOT_EXIST, ENTRY_DOES_NOT_EXIST, FIRST_NOTE_CREATED)
from .models import Note, Entry
from .shemas import entry_schema, entries_schema, note_schema, notes_schema
from .forms import AddFirstNoteForm
from ..accounts.utils import redirect_to_last_updated_note


notes_blueprint = Blueprint('notes', __name__, template_folder='templates')


@notes_blueprint.route('/notes/<note_id>', methods=['GET'])
def note(note_id: int) -> str:
    """The view renders single note page."""
    note = Note.get_by_id(note_id)  # pylint: disable=redefined-outer-name
    if not note or note.user_id != current_user.id:
        abort(404)
    number_of_notes = Note.count_user_notes(current_user.id)
    return render_template('notes/note.html', note=note, number_of_notes=number_of_notes)


@notes_blueprint.route('/notes/<note_id>/export', methods=['GET'])
def note_export(note_id: int) -> str:
    """The view renders note export page where user can download note as pdf."""
    note = Note.get_by_id(note_id)  # pylint: disable=redefined-outer-name
    if not note or note.user_id != current_user.id:
        abort(404)
    number_of_notes = Note.count_user_notes(current_user.id)
    return render_template('notes/export_note.html', note=note, number_of_notes=number_of_notes)


@notes_blueprint.route('/note/first', methods=['GET', 'POST'])
def add_first_note():
    """The view renders page to add first note."""
    number_of_notes = Note.count_user_notes(current_user.id)
    if number_of_notes:
        return redirect_to_last_updated_note()
    form = AddFirstNoteForm()
    if form.validate_on_submit():
        note = Note(title=form.title.data,  # pylint: disable=redefined-outer-name
                    description=form.description.data,
                    user_id=current_user.id)
        note.save_to_db()
        flash(FIRST_NOTE_CREATED, 'error')
        return redirect(url_for('notes.note', note_id=note.id))
    return render_template('notes/add_first_note.html', form=form)


@notes_blueprint.route('/media/notes/img/<year>/<month>/<day>/<filename>')
def media_notes_img(year: str, month: str, day: str, filename: str) -> Response:
    """The view returns note image."""
    image_path = current_app.config['MEDIA_ROOT'] / 'notes' / 'img' / year / month / day
    return send_from_directory(image_path, filename)


@notes_blueprint.route('/media/notes/pdf/<filename>')
def media_notes_pdf(filename: str) -> Response:
    """The view returns note pdf file."""
    return send_from_directory(current_app.config['MEDIA_NOTES_PDF'], filename, as_attachment=True)


@notes_blueprint.route('/api/notes', methods=['GET'])
def load_notes() -> Response:
    """The view returns list of notes as json object."""
    page = request.args.get('npage', 1, type=int)
    pagination = Note.query.filter_by(user_id=current_user.id).order_by(Note.updated.desc()).paginate(
        page,
        per_page=current_app.config['NOTES_PER_PAGE'],
        error_out=False
    )
    notes = notes_schema.dump(pagination.items)
    response_content = {
        'notes': notes,
        'has_next': pagination.has_next,
        'next_num': pagination.next_num
    }
    return make_response(jsonify(response_content), 200)


@notes_blueprint.route('/api/notes', methods=['POST'])
def add_note() -> Response:
    """The view addes new note."""
    if request.is_json:
        data = request.get_json()
        if data:
            try:
                note = note_schema.load(data)  # pylint: disable=redefined-outer-name
                note.user_id = current_user.id
                saved_note = note.save_to_db()
            except ValidationError as error:
                return make_response(jsonify({'error': error.messages}), 400)
            return make_response(jsonify({'note': note_schema.dump(saved_note)}), 200)
        return make_response(jsonify({'error': NO_DATA_TO_ADD}), 400)
    return make_response(jsonify({'error': MISSING_JSON}), 400)


@notes_blueprint.route('/api/notes/<note_id>/entries', methods=['GET'])
def load_entries(note_id: int) -> Response:
    """The view returns list of entries as json object."""
    if not Entry.get_by_note_id(note_id):
        return make_response(jsonify({'error': 'No entries.'}), 200)
    page = request.args.get('epage', 1, type=int)
    pagination = Entry.query.filter_by(note_id=note_id).order_by(Entry.created.desc()).paginate(
        page,
        per_page=current_app.config['ENTRIES_PER_PAGE'],
        error_out=False
    )
    entries = entries_schema.dump(pagination.items)
    response_content = {
        'entries': entries,
        'has_next': pagination.has_next,
        'next_num': pagination.next_num
    }
    return make_response(jsonify(response_content), 200)


@notes_blueprint.route('/api/notes/<note_id>/entries', methods=['POST'])
def add_entry(note_id: int) -> Response:
    """The view addes new entry."""
    if not Note.get_by_id(note_id):
        return make_response(jsonify({'error': NOTE_DOES_NOT_EXIST}), 404)
    if request.is_json:
        data = request.get_json()
        if data:
            try:
                entry = entry_schema.load(data)
            except ValidationError as error:
                return make_response(jsonify({'error': error.messages}), 400)
            entry.note_id = note_id
            saved_entry = entry.save_to_db()
            return make_response(jsonify({'entry': entry_schema.dump(saved_entry)}), 200)
        return make_response(jsonify({'error': NO_DATA_TO_ADD}), 400)
    return make_response(jsonify({'error': MISSING_JSON}), 400)


@notes_blueprint.route('/api/notes/<note_id>/entries/<entry_id>', methods=['PUT'])
def update_entry(note_id: int, entry_id: int) -> Response:
    """The view updates entry."""
    if not Note.get_by_id(note_id):
        return make_response(jsonify({'error': NOTE_DOES_NOT_EXIST}), 404)
    entry = Entry.get_by_id(entry_id)
    if entry and int(entry.note_id) == int(note_id):
        if request.is_json:
            data = request.get_json()
            if data:
                try:
                    validated_entry_data = entry_schema.load(data, partial=True)
                except ValidationError as error:
                    return make_response(jsonify({'error': error.messages}), 400)
                entry.content = validated_entry_data.content  # add update of note_id
                saved_entry = entry.save_to_db()
                return make_response(jsonify({'entry': entry_schema.dump(saved_entry)}), 200)
            return make_response(jsonify({'error': NO_DATA_TO_ADD}), 400)
        return make_response(jsonify({'error': MISSING_JSON}), 400)
    return make_response(jsonify({'error': ENTRY_DOES_NOT_EXIST}), 404)


@notes_blueprint.route('/api/notes/<note_id>/entries/<entry_id>', methods=['DELETE'])
def delete_entry(note_id: int, entry_id: int) -> Response:
    """The view deletes entry."""
    if not Note.get_by_id(note_id):
        return make_response(jsonify({'error': NOTE_DOES_NOT_EXIST}), 404)
    entry = Entry.get_by_id(entry_id)
    if entry:
        response = {'entry': entry_schema.dump(entry)}
        entry.delete_from_db()
        return make_response(jsonify(response), 200)
    return make_response(jsonify({'error': ENTRY_DOES_NOT_EXIST}), 404)


@notes_blueprint.route('/api/notes/<note_id>/export/pdf', methods=['GET'])
def note_export_pdf(note_id: int) -> str:
    """The view generates note pdf."""
    note = Note.get_by_id(note_id)  # pylint: disable=redefined-outer-name
    if not note:
        return make_response(jsonify({'error': NOTE_DOES_NOT_EXIST}), 404)
    from .tasks import generate_note_pdf  # pylint: disable=import-outside-toplevel
    result = generate_note_pdf.delay(note.id)
    return make_response(jsonify({'report_status': 'started', 'task_id': result.id}), 200)


@notes_blueprint.route('/api/task/<task_id>', methods=['GET'])
def task_progress(task_id: str) -> str:
    """The view shows background task progress."""
    from .tasks import generate_note_pdf  # pylint: disable=import-outside-toplevel
    task = generate_note_pdf.AsyncResult(task_id)
    status = task.status
    progress = 0
    result = ''
    if status == 'SUCCESS':
        progress = 100
        result = task.result
    elif status == 'FAILURE':
        progress = 0
    elif status == 'PROGRESS':
        progress = task.info.get('current')
    else:
        status = 'PROGRESS'
    response = {'progress': progress, 'status': status}
    if result:
        response['result'] = f'/media/notes/pdf/{result}'
    return make_response(jsonify(response), 200)

app/notes/templates/notes/add_first_note.html
{% extends "base.html" %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
{% endblock %}


{% block content %}

{% include "includes/header.html" %}

<!-- MAIN PAGE START -->
<div class="jumbotron my-3">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="margin-top: 80px;">
      <div class="col-md-6 col-lg-6 col-xl-6">
        <div class="card rounded-3 text-black">
          <div class="card-body mx-md-4 my-4 pb-1">
            <div class="mb-4">
              <div class="text-center">
              <p class="lead">Your first note</p>
            </div>
              <form method="POST" id="addFirstNoteForm">
                {{ form.csrf_token }}
                <div class="form-outline mb-2">
                {{ form.title.label(class_="form-label") }}
                {{ form.title(class_="form-control", id_="firstNoteTitle", placeholder="Enter your note title") }}
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="form-outline mb-2">
                {{ form.description.label(class_="form-label") }}
                {{ form.description(class_="form-control", id_="firstNoteDescription", placeholder="Enter short description") }}
                {% for error in form.description.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                <div class="text-center mb-2">
                  <div class="d-grid gap-2">
                    <button class="btn btn-dark mb-2" type="submit">Add note</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- MAIN PAGE END -->

{% endblock %}


{% block js %}

<script src="{{ url_for('static', filename='js/header.bundle.js') }}"></script>

{% endblock %}

app/notes/templates/notes/export_note.html
{% extends "base.html" %}

{% from "includes/quill_editor.html" import quill_editor %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
{% endblock %}


{% block content %}

{% include "includes/header.html" %}

<!-- MAIN PAGE START -->
<div class="jumbotron my-3">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="margin-top: 80px;">
      <div class="col-md-6 col-lg-6 col-xl-6">
        <div class="card rounded-3 text-black">
          <div class="card-body mx-md-4 my-4 pb-1">
            <div class="">
              <p class="lead">Dump your note to PDF file and download it</p>
            </div>
            <div class="shadow p-3 mb-3 bg-body rounded">
              <h4 class="text-secondary">{{ note.title }}</h4>
              <p class="text-secondary" style="font-size: 0.8rem;">{{ note.description }}</p>
              <small><i>Here we will put list of your entries...</i></small>
            </div>
            <div class="mb-3">
              <a href="{{ url_for('notes.note', note_id=note.id) }}" class="text-dark">See note details</a>
            </div>
            <div class="d-grid gap-2 mt-4">
              <div class="collapse mb-2" id="collapseProgress">
                <div class="progress" style="height: 10px;">
                  <div class="progress-bar bg-dark" id="progressBar" role="progressbar" style="width: 0%;" 
                       aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
              <button class="btn btn-dark" id="generateButton" type="button">
                Generate PDF
              </button>
              <div class="collapse" id="collapseResult">
                <div class="text-center mb-4 pt-4">
                  <a class="text-dark" id="downloadLink" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" 
                         class="bi bi-filetype-pdf" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 
                                                   1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM1.6 11.85H0v3.999h.791v-1.342h.803c.287 0 
                                                   .531-.057.732-.173.203-.117.358-.275.463-.474a1.42 1.42 0 0 0 
                                                   .161-.677c0-.25-.053-.476-.158-.677a1.176 1.176 0 0 0-.46-.477c-.2-.12-.443-.179-.732-.179Zm.545 
                                                   1.333a.795.795 0 0 1-.085.38.574.574 0 0 1-.238.241.794.794 0 0 1-.375.082H.788V12.48h.66c.218 
                                                   0 .389.06.512.181.123.122.185.296.185.522Zm1.217-1.333v3.999h1.46c.401 0 .734-.08.998-.237a1.45 
                                                   1.45 0 0 0 .595-.689c.13-.3.196-.662.196-1.084 0-.42-.065-.778-.196-1.075a1.426 1.426 0 0 
                                                   0-.589-.68c-.264-.156-.599-.234-1.005-.234H3.362Zm.791.645h.563c.248 0 .45.05.609.152a.89.89 
                                                   0 0 1 .354.454c.079.201.118.452.118.753a2.3 2.3 0 0 1-.068.592 1.14 1.14 0 0 1-.196.422.8.8 0 
                                                   0 1-.334.252 1.298 1.298 0 0 1-.483.082h-.563v-2.707Zm3.743 
                                                   1.763v1.591h-.79V11.85h2.548v.653H7.896v1.117h1.606v.638H7.896Z"/>
                    </svg>
                    <p class="">Download</p>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- MAIN PAGE END -->

{% endblock %}


{% block js %}

<script src="{{ url_for('static', filename='js/export_note.bundle.js') }}"></script>

<script src="{{ url_for('static', filename='js/header.bundle.js') }}"></script>

{% endblock %}

app/notes/templates/notes/note.html
{% extends "base.html" %}

{% from "includes/quill_editor.html" import quill_editor %}

{% block title %}<title>Keepno</title>{% endblock %}

{% block style %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<style>
  .separator {
    display: flex;
    align-items: center;
    text-align: center;
    font-size: 0.7rem;
    color: rgb(189, 189, 189);
  }

  .separator::before,
  .separator::after {
    content: '';
    flex: 1;
    border-bottom: 1px solid rgb(189, 189, 189);
  }

  .separator:not(:empty)::before {
    margin-right: .25em;
  }

  .separator:not(:empty)::after {
    margin-left: .25em;
  }
</style>
{% endblock %}


{% block content %}

{% include "includes/header.html" %}

<!-- MAIN PAGE START -->
<main>
  <div class="px-3 pt-2" style="max-width: 800px; margin-left: auto; margin-right: auto;">
    <div class="row" style="margin-top: 60px;">
      <div class="col">
        <h1 class="display-5">{{ note.title }}</h1>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3" 
             style="font-size: 0.8rem;">
          <span>{{ note.description }}</span>
          <div class="btn-toolbar mt-1 mb-2 mb-md-0">
            <div class="btn-group" role="group" aria-label="Basic example">
              <button class="btn btn-outline-dark btn-sm" type="button" data-bs-toggle="modal" 
                      data-bs-target="#addEntryModal" data-bs-whatever="@mdo">Add&nbsp;entry</button>
              <a role="button" class="btn btn-outline-dark btn-sm" href="{{ url_for('notes.note_export', note_id=note.id) }}">Export</a>
              <button class="btn btn-outline-dark btn-sm" type="button">Share</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <!-- entries list start -->
        <div id="entries" class="mb-3">
          <template id="entries-template">
            <div id="entryRow">
              <div class="row">
                <div class="col">
                  <div class="separator" id="created"></div>
                </div>
              </div>
              <div class="row pb-3">
                <div class="col" style="width: 100%; padding-right: 0.3rem">
                  <div id="content"></div>
                </div>
                <div class="col-auto" style="padding-left: 0px;">
                  <div class="dropdown">
                    <a class="text-dark" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" 
                           class="bi bi-three-dots-vertical" viewBox="0 0 10 16">
                        <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 
                                 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                      </svg>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <li>
                        <a class="dropdown-item" id="deleteEntryLink" href="" data-bs-toggle="modal" 
                           data-bs-target="#deleteEntryModal" data-entryid="#">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
                               class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 
                                     .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 
                                                         1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 
                                                         1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 
                                                         1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                          </svg>
                          Delete
                        </a>
                      </li>
                      <li>
                        <a class="dropdown-item" id="updateEntryLink" href="" data-bs-toggle="modal" 
                        data-bs-target="#updateEntryModal" data-entryid="#">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
                               class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 
                                     2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 
                                     3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 
                                     .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 
                                     3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 
                                     0 0 1-.468-.325z"/>
                          </svg>
                          Edit
                        </a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="#">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
                               class="bi bi-clipboard" viewBox="0 0 16 16">
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 
                                     0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 
                                     .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 
                                     2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                          </svg>
                          Copy
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </template>
        </div>
        <!-- entries list end -->
      </div>
    </div>
    <div class="row" id="entries-loading-spiner">
      <div class="col">
        <div class="d-flex justify-content-center mb-3">
          <div class="spinner-border" role="status"></div>
        </div>
      </div>
    </div>
  </div>
</main>
<!-- MAIN PAGE END -->


<!-- ADD NEW ENTRY MODAL START -->
<div class="modal fade bd-example-modal-xl" id="addEntryModal" tabindex="-1" 
     aria-labelledby="addEntryModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addEntryModalLabel">New Entry</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          {{ quill_editor("add-standalone-container", "add-toolbar-container", "add-editor-container") }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" id="save-entry" class="btn btn-dark">Add Entry</button>
      </div>
    </div>
  </div>
</div>
<!-- ADD NEW ENTRY MODAL END -->

<!-- UPDATE ENTRY MODAL START -->
<div class="modal fade bd-example-modal-xl" id="updateEntryModal" tabindex="-1" 
     aria-labelledby="updateEntryModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateEntryModalLabel">Update Entry</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          {{ quill_editor("update-standalone-container", "update-toolbar-container", "update-editor-container") }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" id="updateEntryButton" class="btn btn-dark">Update Entry</button>
      </div>
    </div>
  </div>
</div>
<!-- UPDATE ENTRY MODAL END -->

<!-- DELETE ENTRY MODAL START -->
<div class="modal fade" id="deleteEntryModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Entry will be deleted</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Do you want to delete this entry?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" id="deleteEntryButton" class="btn btn-dark" data-entryid="#">Delete</button>
      </div>
    </div>
  </div>
</div>
<!-- DELETE ENTRY MODAL END -->

{% endblock %}


{% block js %}

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<script src="{{ url_for('static', filename='js/note.bundle.js') }}"></script>

<script src="{{ url_for('static', filename='js/header.bundle.js') }}"></script>

{% endblock %}